# A demo CRD for the Kopf example operators.
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: awsauthmappings.tier.app
spec:
  scope: Cluster
  group: tier.app
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                mappings:
                  type: array
                  items:
                    type: object
                    properties:
                      arn:
                        type: string
                      username:
                        type: string
                      usertype:
                        type: string
                        enum: [ Role, User ]
                      groups:
                        type: array
                        items:
                          type: string
  names:
    kind: AwsAuthMapping
    plural: awsauthmappings
    singular: awsauthmapping
    shortNames:
      - awsmapping
      - awsm
