
replicaCount: 1

image:
  repository: ghcr.io/vinivia/aws-auth-operator
  tag: latest
  pullPolicy: Always

alerts:
  enabled: false

healthcheck:
  port: 8080
env:
  variables:
    data:
      USE_PROTECTED_MAPPING: true

resources:
  limits:
    cpu: 50m
  requests:
    cpu: 10m


#nodeSelector:
#
#affinity:
#
#tolerations:
